-- Generado por Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   en:        2026-07-19 16:18:50 CST
--   sitio:      Oracle Database 21c
--   tipo:      Oracle Database 21c



CREATE USER SYSTEM 
    IDENTIFIED BY  
    ACCOUNT UNLOCK 
;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE SYSTEM.CARTA_AUTORIZACION_MENOR 
    ( 
     ID_CARTA        NUMBER GENERATED ALWAYS AS IDENTITY 
        ( START WITH 1 CACHE 20 )  NOT NULL , 
     ID_PERSONA      NUMBER  NOT NULL , 
     NOMBRE_AUTORIZA VARCHAR2 (100 BYTE)  NOT NULL , 
     CUI_AUTORIZA    VARCHAR2 (13 BYTE)  NOT NULL , 
     PARENTESCO      VARCHAR2 (30 BYTE)  NOT NULL , 
     FECHA_EMISION   DATE  NOT NULL 
    ) 
        PCTFREE 10 
        PCTUSED 40 
        TABLESPACE SYSTEM 
        LOGGING 
        STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
    ) 
    NO INMEMORY 
;

COMMENT ON TABLE SYSTEM.CARTA_AUTORIZACION_MENOR IS 'Carta de autorización del padre/tutor, requerida solo cuando el titular es menor de edad'
;
CREATE UNIQUE INDEX SYSTEM.PK_CARTA_AUTORIZACION ON SYSTEM.CARTA_AUTORIZACION_MENOR 
    ( 
     ID_CARTA ASC 
    ) 
    TABLESPACE SYSTEM 
    PCTFREE 10 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING 
;
CREATE UNIQUE INDEX SYSTEM.UQ_CARTA_PERSONA ON SYSTEM.CARTA_AUTORIZACION_MENOR 
    ( 
     ID_PERSONA ASC 
    ) 
    TABLESPACE SYSTEM 
    PCTFREE 10 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING 
;

ALTER TABLE SYSTEM.CARTA_AUTORIZACION_MENOR 
    ADD CONSTRAINT PK_CARTA_AUTORIZACION PRIMARY KEY ( ID_CARTA ) 
    USING INDEX SYSTEM.PK_CARTA_AUTORIZACION ;

ALTER TABLE SYSTEM.CARTA_AUTORIZACION_MENOR 
    ADD CONSTRAINT UQ_CARTA_PERSONA UNIQUE ( ID_PERSONA ) 
    USING INDEX SYSTEM.UQ_CARTA_PERSONA ;

CREATE TABLE SYSTEM.EXAMEN 
    ( 
     ID_EXAMEN        NUMBER GENERATED ALWAYS AS IDENTITY 
        ( START WITH 1 CACHE 20 )  NOT NULL , 
     ID_PERSONA       NUMBER  NOT NULL , 
     ID_TIPO_EXAMEN   NUMBER  NOT NULL , 
     ID_TIPO_LICENCIA NUMBER  NOT NULL , 
     FECHA_EXAMEN     DATE  NOT NULL , 
     RESULTADO        VARCHAR2 (10 BYTE)  NOT NULL , 
     NOTA             NUMBER (5,2) 
    ) 
        PCTFREE 10 
        PCTUSED 40 
        TABLESPACE SYSTEM 
        LOGGING 
        STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
    ) 
    NO INMEMORY 
;

ALTER TABLE SYSTEM.EXAMEN 
    ADD CONSTRAINT CK_EXAMEN_RESULTADO 
    CHECK (RESULTADO IN ('APROBADO', 'REPROBADO')) 
;

COMMENT ON TABLE SYSTEM.EXAMEN IS 'Examen teórico, práctico o de la vista presentado por una persona para un tipo de licencia'
;
CREATE UNIQUE INDEX SYSTEM.PK_EXAMEN ON SYSTEM.EXAMEN 
    ( 
     ID_EXAMEN ASC 
    ) 
    TABLESPACE SYSTEM 
    PCTFREE 10 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING 
;

ALTER TABLE SYSTEM.EXAMEN 
    ADD CONSTRAINT PK_EXAMEN PRIMARY KEY ( ID_EXAMEN ) 
    USING INDEX SYSTEM.PK_EXAMEN ;

CREATE TABLE SYSTEM.LICENCIA 
    ( 
     ID_LICENCIA       NUMBER GENERATED ALWAYS AS IDENTITY 
        ( START WITH 1 CACHE 20 )  NOT NULL , 
     NUMERO_LICENCIA   VARCHAR2 (20 BYTE)  NOT NULL , 
     ID_PERSONA        NUMBER  NOT NULL , 
     ID_TIPO_LICENCIA  NUMBER  NOT NULL , 
     FECHA_EMISION     DATE  NOT NULL , 
     FECHA_VENCIMIENTO DATE  NOT NULL , 
     ESTADO            VARCHAR2 (10 BYTE) DEFAULT 'VIGENTE'  NOT NULL 
    ) 
        PCTFREE 10 
        PCTUSED 40 
        TABLESPACE SYSTEM 
        LOGGING 
        STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
    ) 
    NO INMEMORY 
;

ALTER TABLE SYSTEM.LICENCIA 
    ADD CONSTRAINT CK_LICENCIA_ESTADO 
    CHECK (ESTADO IN ('VENCIDA', 'VIGENTE')) 
;

COMMENT ON COLUMN SYSTEM.LICENCIA.FECHA_VENCIMIENTO IS 'El vencimiento siempre cae en el día de cumpleaños del titular' 
;
CREATE UNIQUE INDEX SYSTEM.PK_LICENCIA ON SYSTEM.LICENCIA 
    ( 
     ID_LICENCIA ASC 
    ) 
    TABLESPACE SYSTEM 
    PCTFREE 10 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING 
;
CREATE UNIQUE INDEX SYSTEM.UQ_LICENCIA_NUMERO ON SYSTEM.LICENCIA 
    ( 
     NUMERO_LICENCIA ASC 
    ) 
    TABLESPACE SYSTEM 
    PCTFREE 10 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING 
;
CREATE UNIQUE INDEX SYSTEM.UQ_LICENCIA_PERSONA_TIPO ON SYSTEM.LICENCIA 
    ( 
     ID_PERSONA ASC , 
     ID_TIPO_LICENCIA ASC 
    ) 
    TABLESPACE SYSTEM 
    PCTFREE 10 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING 
;

ALTER TABLE SYSTEM.LICENCIA 
    ADD CONSTRAINT PK_LICENCIA PRIMARY KEY ( ID_LICENCIA ) 
    USING INDEX SYSTEM.PK_LICENCIA ;

ALTER TABLE SYSTEM.LICENCIA 
    ADD CONSTRAINT UQ_LICENCIA_NUMERO UNIQUE ( NUMERO_LICENCIA ) 
    USING INDEX SYSTEM.UQ_LICENCIA_NUMERO ;

ALTER TABLE SYSTEM.LICENCIA 
    ADD CONSTRAINT UQ_LICENCIA_PERSONA_TIPO UNIQUE ( ID_PERSONA , ID_TIPO_LICENCIA ) 
    USING INDEX SYSTEM.UQ_LICENCIA_PERSONA_TIPO ;

CREATE TABLE SYSTEM.PAGO 
    ( 
     ID_PAGO       NUMBER GENERATED ALWAYS AS IDENTITY 
        ( START WITH 1 CACHE 20 )  NOT NULL , 
     ID_RENOVACION NUMBER  NOT NULL , 
     MONTO_PAGADO  NUMBER (8,2)  NOT NULL , 
     FECHA_PAGO    DATE  NOT NULL , 
     FORMA_PAGO    VARCHAR2 (20 BYTE)  NOT NULL , 
     NUMERO_BOLETA VARCHAR2 (30 BYTE) 
    ) 
        PCTFREE 10 
        PCTUSED 40 
        TABLESPACE SYSTEM 
        LOGGING 
        STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
    ) 
    NO INMEMORY 
;

ALTER TABLE SYSTEM.PAGO 
    ADD CONSTRAINT CK_PAGO_FORMA 
    CHECK (FORMA_PAGO IN ('EFECTIVO', 'TARJETA', 'TRANSFERENCIA')) 
;
CREATE UNIQUE INDEX SYSTEM.PK_PAGO ON SYSTEM.PAGO 
    ( 
     ID_PAGO ASC 
    ) 
    TABLESPACE SYSTEM 
    PCTFREE 10 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING 
;
CREATE UNIQUE INDEX SYSTEM.UQ_PAGO_RENOVACION ON SYSTEM.PAGO 
    ( 
     ID_RENOVACION ASC 
    ) 
    TABLESPACE SYSTEM 
    PCTFREE 10 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING 
;

ALTER TABLE SYSTEM.PAGO 
    ADD CONSTRAINT PK_PAGO PRIMARY KEY ( ID_PAGO ) 
    USING INDEX SYSTEM.PK_PAGO ;

ALTER TABLE SYSTEM.PAGO 
    ADD CONSTRAINT UQ_PAGO_RENOVACION UNIQUE ( ID_RENOVACION ) 
    USING INDEX SYSTEM.UQ_PAGO_RENOVACION ;

CREATE TABLE SYSTEM.PERSONA 
    ( 
     ID_PERSONA       NUMBER GENERATED ALWAYS AS IDENTITY 
        ( START WITH 1 CACHE 20 )  NOT NULL , 
     CUI              VARCHAR2 (13 BYTE)  NOT NULL , 
     PRIMER_NOMBRE    VARCHAR2 (50 BYTE)  NOT NULL , 
     SEGUNDO_NOMBRE   VARCHAR2 (50 BYTE) , 
     PRIMER_APELLIDO  VARCHAR2 (50 BYTE)  NOT NULL , 
     SEGUNDO_APELLIDO VARCHAR2 (50 BYTE) , 
     FECHA_NACIMIENTO DATE  NOT NULL , 
     GENERO           CHAR (1 BYTE)  NOT NULL , 
     DIRECCION        VARCHAR2 (150 BYTE) , 
     TELEFONO         VARCHAR2 (15 BYTE) 
    ) 
        PCTFREE 10 
        PCTUSED 40 
        TABLESPACE SYSTEM 
        LOGGING 
        STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
    ) 
    NO INMEMORY 
;

ALTER TABLE SYSTEM.PERSONA 
    ADD CONSTRAINT CK_PERSONA_GENERO 
    CHECK (GENERO IN ('F', 'M')) 
;

COMMENT ON TABLE SYSTEM.PERSONA IS 'Personas que solicitan u obtienen una licencia de conducir'
;

COMMENT ON COLUMN SYSTEM.PERSONA.FECHA_NACIMIENTO IS 'Se usa para calcular edad y fecha de vencimiento (cumpleaños)' 
;
CREATE UNIQUE INDEX SYSTEM.PK_PERSONA ON SYSTEM.PERSONA 
    ( 
     ID_PERSONA ASC 
    ) 
    TABLESPACE SYSTEM 
    PCTFREE 10 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING 
;
CREATE UNIQUE INDEX SYSTEM.UQ_PERSONA_CUI ON SYSTEM.PERSONA 
    ( 
     CUI ASC 
    ) 
    TABLESPACE SYSTEM 
    PCTFREE 10 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING 
;

ALTER TABLE SYSTEM.PERSONA 
    ADD CONSTRAINT PK_PERSONA PRIMARY KEY ( ID_PERSONA ) 
    USING INDEX SYSTEM.PK_PERSONA ;

ALTER TABLE SYSTEM.PERSONA 
    ADD CONSTRAINT UQ_PERSONA_CUI UNIQUE ( CUI ) 
    USING INDEX SYSTEM.UQ_PERSONA_CUI ;

CREATE TABLE SYSTEM.RENOVACION 
    ( 
     ID_RENOVACION              NUMBER GENERATED ALWAYS AS IDENTITY 
        ( START WITH 1 CACHE 20 )  NOT NULL , 
     ID_LICENCIA                NUMBER  NOT NULL , 
     ID_TARIFA                  NUMBER  NOT NULL , 
     FECHA_RENOVACION           DATE  NOT NULL , 
     FECHA_VENCIMIENTO_ANTERIOR DATE  NOT NULL , 
     FECHA_VENCIMIENTO_NUEVA    DATE  NOT NULL 
    ) 
        PCTFREE 10 
        PCTUSED 40 
        TABLESPACE SYSTEM 
        LOGGING 
        STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
    ) 
    NO INMEMORY 
;
CREATE UNIQUE INDEX SYSTEM.PK_RENOVACION ON SYSTEM.RENOVACION 
    ( 
     ID_RENOVACION ASC 
    ) 
    TABLESPACE SYSTEM 
    PCTFREE 10 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING 
;

ALTER TABLE SYSTEM.RENOVACION 
    ADD CONSTRAINT PK_RENOVACION PRIMARY KEY ( ID_RENOVACION ) 
    USING INDEX SYSTEM.PK_RENOVACION ;

CREATE TABLE SYSTEM.TARIFA_RENOVACION 
    ( 
     ID_TARIFA NUMBER GENERATED ALWAYS AS IDENTITY 
        ( START WITH 1 CACHE 20 )  NOT NULL , 
     ANIOS     NUMBER (1)  NOT NULL , 
     MONTO     NUMBER (8,2)  NOT NULL 
    ) 
        PCTFREE 10 
        PCTUSED 40 
        TABLESPACE SYSTEM 
        LOGGING 
        STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
    ) 
    NO INMEMORY 
;

ALTER TABLE SYSTEM.TARIFA_RENOVACION 
    ADD CONSTRAINT CK_TARIFA_ANIOS 
    CHECK (ANIOS BETWEEN 1 AND 5) 
;
CREATE UNIQUE INDEX SYSTEM.PK_TARIFA_RENOVACION ON SYSTEM.TARIFA_RENOVACION 
    ( 
     ID_TARIFA ASC 
    ) 
    TABLESPACE SYSTEM 
    PCTFREE 10 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING 
;
CREATE UNIQUE INDEX SYSTEM.UQ_TARIFA_ANIOS ON SYSTEM.TARIFA_RENOVACION 
    ( 
     ANIOS ASC 
    ) 
    TABLESPACE SYSTEM 
    PCTFREE 10 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING 
;

ALTER TABLE SYSTEM.TARIFA_RENOVACION 
    ADD CONSTRAINT PK_TARIFA_RENOVACION PRIMARY KEY ( ID_TARIFA ) 
    USING INDEX SYSTEM.PK_TARIFA_RENOVACION ;

ALTER TABLE SYSTEM.TARIFA_RENOVACION 
    ADD CONSTRAINT UQ_TARIFA_ANIOS UNIQUE ( ANIOS ) 
    USING INDEX SYSTEM.UQ_TARIFA_ANIOS ;

CREATE TABLE SYSTEM.TIPO_EXAMEN 
    ( 
     ID_TIPO_EXAMEN NUMBER GENERATED ALWAYS AS IDENTITY 
        ( START WITH 1 CACHE 20 )  NOT NULL , 
     NOMBRE         VARCHAR2 (50 BYTE)  NOT NULL 
    ) 
        PCTFREE 10 
        PCTUSED 40 
        TABLESPACE SYSTEM 
        LOGGING 
        STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
    ) 
    NO INMEMORY 
;
CREATE UNIQUE INDEX SYSTEM.PK_TIPO_EXAMEN ON SYSTEM.TIPO_EXAMEN 
    ( 
     ID_TIPO_EXAMEN ASC 
    ) 
    TABLESPACE SYSTEM 
    PCTFREE 10 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING 
;
CREATE UNIQUE INDEX SYSTEM.UQ_TIPO_EXAMEN_NOMBRE ON SYSTEM.TIPO_EXAMEN 
    ( 
     NOMBRE ASC 
    ) 
    TABLESPACE SYSTEM 
    PCTFREE 10 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING 
;

ALTER TABLE SYSTEM.TIPO_EXAMEN 
    ADD CONSTRAINT PK_TIPO_EXAMEN PRIMARY KEY ( ID_TIPO_EXAMEN ) 
    USING INDEX SYSTEM.PK_TIPO_EXAMEN ;

ALTER TABLE SYSTEM.TIPO_EXAMEN 
    ADD CONSTRAINT UQ_TIPO_EXAMEN_NOMBRE UNIQUE ( NOMBRE ) 
    USING INDEX SYSTEM.UQ_TIPO_EXAMEN_NOMBRE ;

CREATE TABLE SYSTEM.TIPO_LICENCIA 
    ( 
     ID_TIPO_LICENCIA NUMBER GENERATED ALWAYS AS IDENTITY 
        ( START WITH 1 CACHE 20 )  NOT NULL , 
     CODIGO           VARCHAR2 (1 BYTE)  NOT NULL , 
     DESCRIPCION      VARCHAR2 (100 BYTE)  NOT NULL 
    ) 
        PCTFREE 10 
        PCTUSED 40 
        TABLESPACE SYSTEM 
        LOGGING 
        STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
    ) 
    NO INMEMORY 
;

ALTER TABLE SYSTEM.TIPO_LICENCIA 
    ADD CONSTRAINT CK_TIPO_LICENCIA_CODIGO 
    CHECK (CODIGO IN ('A', 'B', 'C', 'M')) 
;
CREATE UNIQUE INDEX SYSTEM.PK_TIPO_LICENCIA ON SYSTEM.TIPO_LICENCIA 
    ( 
     ID_TIPO_LICENCIA ASC 
    ) 
    TABLESPACE SYSTEM 
    PCTFREE 10 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING 
;
CREATE UNIQUE INDEX SYSTEM.UQ_TIPO_LICENCIA_CODIGO ON SYSTEM.TIPO_LICENCIA 
    ( 
     CODIGO ASC 
    ) 
    TABLESPACE SYSTEM 
    PCTFREE 10 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    LOGGING 
;

ALTER TABLE SYSTEM.TIPO_LICENCIA 
    ADD CONSTRAINT PK_TIPO_LICENCIA PRIMARY KEY ( ID_TIPO_LICENCIA ) 
    USING INDEX SYSTEM.PK_TIPO_LICENCIA ;

ALTER TABLE SYSTEM.TIPO_LICENCIA 
    ADD CONSTRAINT UQ_TIPO_LICENCIA_CODIGO UNIQUE ( CODIGO ) 
    USING INDEX SYSTEM.UQ_TIPO_LICENCIA_CODIGO ;

ALTER TABLE SYSTEM.CARTA_AUTORIZACION_MENOR 
    ADD CONSTRAINT FK_CARTA_PERSONA FOREIGN KEY 
    ( 
     ID_PERSONA
    ) 
    REFERENCES SYSTEM.PERSONA 
    ( 
     ID_PERSONA
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE SYSTEM.EXAMEN 
    ADD CONSTRAINT FK_EXAMEN_PERSONA FOREIGN KEY 
    ( 
     ID_PERSONA
    ) 
    REFERENCES SYSTEM.PERSONA 
    ( 
     ID_PERSONA
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE SYSTEM.EXAMEN 
    ADD CONSTRAINT FK_EXAMEN_TIPO_EXAMEN FOREIGN KEY 
    ( 
     ID_TIPO_EXAMEN
    ) 
    REFERENCES SYSTEM.TIPO_EXAMEN 
    ( 
     ID_TIPO_EXAMEN
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE SYSTEM.EXAMEN 
    ADD CONSTRAINT FK_EXAMEN_TIPO_LICENCIA FOREIGN KEY 
    ( 
     ID_TIPO_LICENCIA
    ) 
    REFERENCES SYSTEM.TIPO_LICENCIA 
    ( 
     ID_TIPO_LICENCIA
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE SYSTEM.LICENCIA 
    ADD CONSTRAINT FK_LICENCIA_PERSONA FOREIGN KEY 
    ( 
     ID_PERSONA
    ) 
    REFERENCES SYSTEM.PERSONA 
    ( 
     ID_PERSONA
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE SYSTEM.LICENCIA 
    ADD CONSTRAINT FK_LICENCIA_TIPO FOREIGN KEY 
    ( 
     ID_TIPO_LICENCIA
    ) 
    REFERENCES SYSTEM.TIPO_LICENCIA 
    ( 
     ID_TIPO_LICENCIA
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE SYSTEM.PAGO 
    ADD CONSTRAINT FK_PAGO_RENOVACION FOREIGN KEY 
    ( 
     ID_RENOVACION
    ) 
    REFERENCES SYSTEM.RENOVACION 
    ( 
     ID_RENOVACION
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE SYSTEM.RENOVACION 
    ADD CONSTRAINT FK_RENOVACION_LICENCIA FOREIGN KEY 
    ( 
     ID_LICENCIA
    ) 
    REFERENCES SYSTEM.LICENCIA 
    ( 
     ID_LICENCIA
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE SYSTEM.RENOVACION 
    ADD CONSTRAINT FK_RENOVACION_TARIFA FOREIGN KEY 
    ( 
     ID_TARIFA
    ) 
    REFERENCES SYSTEM.TARIFA_RENOVACION 
    ( 
     ID_TARIFA
    ) 
    NOT DEFERRABLE 
;



-- Informe de Resumen de Oracle SQL Developer Data Modeler: 
-- 
-- CREATE TABLE                             9
-- CREATE INDEX                            17
-- ALTER TABLE                             32
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              1
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
